name: Deploy Services

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      - 'chat-server/**'
      - '.github/workflows/deploy.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Auth Image
        uses: docker/build-push-action@v5
        with:
          context: ./auth
          file: ./auth/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/kornilovivan/auth:latest

      - name: Build and Push Chat-Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./chat-server
          file: ./chat-server/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/kornilovivan/chat-server:latest

  deploy-auth:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy Auth to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Логинимся в ghcr.io
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 2. Скачиваем свежий образ auth
            docker pull ghcr.io/kornilovivan/auth:latest

            # 3. Перезапускаем контейнер auth-app
            docker stop auth-app || true
            docker rm auth-app || true

            docker run -d \
              --name auth-app \
              --network app-net \
              -p 50051:50051 \
              -e GRPC_HOST=0.0.0.0 \
              -e GRPC_PORT=50051 \
              -e "PG_DSN=host=pg port=5432 dbname=auth user=auth-user password=auth-password sslmode=disable" \
              --restart unless-stopped \
              ghcr.io/kornilovivan/auth:latest
